### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by G6KG** [knowbee/llvd#101]
Current: 02-Setup and Configuration/02-Finding a C library.mp4 @720p
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/llvd/app.py", line 221, in download_entire_course
    download_video(download_url, video_index, video_name, chapter_path, delay)
  File "/opt/homebrew/lib/python3.10/site-packages/llvd/downloader.py", line 31, in download_video
    total=int(download_size),
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/llvd/app.py", line 221, in download_entire_course
    download_video(download_url, video_index, video_name, chapter_path, delay)
  File "/opt/homebrew/lib/python3.10/site-packages/llvd/downloader.py", line 31, in download_video
    total=int(download_size),
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by knowbee** [comment]
Can you share with me the course you were trying to download when this error occurred ?

**Comment by knowbee** [comment]
#113
