### ISSUE TITLE
when i try to download I get this error unsupported format string passed to NoneType.__format__

### ISSUE THREAD

**Issue by ALEXDINO7** [knowbee/llvd#103]
unsupported format string passed to NoneType.__format__

after i use the script

**Comment by knowbee** [comment]
Can you provide more information on how exactly this error occurred what were you trying to download?

**Comment by onehex** [comment]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hx\venv\llvd\lib\site-packages\llvd\app.py", line 221, in download_entire_course
    download_video(download_url, video_index, video_name, chapter_path, delay)
  File "C:\Users\hx\venv\llvd\lib\site-packages\llvd\downloader.py", line 31, in download_video
    total=int(download_size),
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by sapkotaj** [comment]
Please make sure you have copied the correct cookies especially li_at. I got the same issue and found out that the cookie value for li_at was wrong. After I fixed the cookies, it started working.

**Comment by onehex** [comment]
thank you @knowbee
