### ISSUE TITLE
Reattempts downloading entire course multiple times on type error

### ISSUE THREAD

**Issue by phommata** [knowbee/llvd#110]
When the below type error occurs, the entire course download is reattempted about 3 times. This eats up into the API limit. Can we have this move onto the next video when this occurs?

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/llvd/app.py", line 221, in download_entire_course
    download_video(download_url, video_index, video_name, chapter_path, delay)
  File "/usr/local/lib/python3.9/site-packages/llvd/downloader.py", line 31, in download_video
    total=int(download_size),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/llvd/app.py", line 221, in download_entire_course
    download_video(download_url, video_index, video_name, chapter_path, delay)
  File "/usr/local/lib/python3.9/site-packages/llvd/downloader.py", line 31, in download_video
    total=int(download_size),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/llvd/app.py", line 221, in download_entire_course
    download_video(download_url, video_index, video_name, chapter_path, delay)
  File "/usr/local/lib/python3.9/site-packages/llvd/downloader.py", line 31, in download_video
    total=int(download_size),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/llvd/app.py", line 221, in download_entire_course
    download_video(download_url, video_index, video_name, chapter_path, delay)
  File "/usr/local/lib/python3.9/site-packages/llvd/downloader.py", line 31, in download_video
    total=int(download_size),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/llvd/app.py", line 221, in download_entire_course
    download_video(download_url, video_index, video_name, chapter_path, delay)
  File "/usr/local/lib/python3.9/site-packages/llvd/downloader.py", line 31, in download_video
    total=int(download_size),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/llvd/app.py", line 221, in download_entire_course
    download_video(download_url, video_index, video_name, chapter_path, delay)
  File "/usr/local/lib/python3.9/site-packages/llvd/downloader.py", line 31, in download_video
    total=int(download_size),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/llvd/app.py", line 221, in download_entire_course
    download_video(download_url, video_index, video_name, chapter_path, delay)
  File "/usr/local/lib/python3.9/site-packages/llvd/downloader.py", line 31, in download_video
    total=int(download_size),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/llvd/app.py", line 221, in download_entire_course
    download_video(download_url, video_index, video_name, chapter_path, delay)
  File "/usr/local/lib/python3.9/site-packages/llvd/downloader.py", line 31, in download_video
    total=int(download_size),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by phommata** [comment]
Installed the latest version. No longer an issue.
