### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by FebboR** [knowbee/llvd#111]
Current: 05-SwiftUI Binding/01-Getting text input with SwiftUI.mp4 @720p
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/llvd/app.py", line 221, in download_entire_course
    download_video(download_url, video_index, video_name, chapter_path, delay)
  File "/opt/homebrew/lib/python3.10/site-packages/llvd/downloader.py", line 31, in download_video
    total=int(download_size),
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

It happens very often this error, usually then when it starts again on the next attempt it succeeds in downloading the video, but on the next video it returns the same error and so on.

**Comment by knowbee** [comment]
#113
