### ISSUE TITLE
UnboundLocalError: cannot access local variable 'current_files' where it is not associated with a value

### ISSUE THREAD

**Issue by WoodpeckerBaby** [knowbee/llvd#112]
macOS 13.4 terminal 

`llvd -c "introduction-to-photography" --cookies --caption -t 10,30`

The file folder is on the desktop. 

I trid deleting the folder and downloading again, same results after awhile. 

<details>

```
Using cookie info from cookies.txt

Current: 0. Welcome/01. Introduction.mp4 @720p
Skipping already existing video...
Downloading subtitles..

Current: 1. Cameras and Lenses/01. Understanding the basics of a camera.mp4 @720p
Skipping already existing video...
Downloading subtitles..

Current: 1. Cameras and Lenses/02. Exploring the basics of a DSLR.mp4 @720p
Skipping already existing video...
Downloading subtitles..

Current: 1. Cameras and Lenses/03. Understanding mirrorless cameras.mp4 @720p
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Downloading video... : 100%|✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹✹| 20.5M/20.5M [00:04<00:00, 4.18MB/s]
Downloading subtitles..
This video is locked, you probably need a premium account
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 336, in download_entire_course
    self.fetch_chapter(chapter, chapters_pad_length, delay)
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 282, in fetch_chapter
    if clean_name(video_name) not in current_files:
                                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'current_files' where it is not associated with a value

Current: 0. Welcome/01. Introduction.mp4 @720p
Skipping already existing video...
Downloading subtitles..

Current: 1. Cameras and Lenses/01. Understanding the basics of a camera.mp4 @720p
Skipping already existing video...
Downloading subtitles..

Current: 1. Cameras and Lenses/02. Exploring the basics of a DSLR.mp4 @720p
Skipping already existing video...
Downloading subtitles..

Current: 1. Cameras and Lenses/03. Understanding mirrorless cameras.mp4 @720p
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 336, in download_entire_course
    self.fetch_chapter(chapter, chapters_pad_length, delay)
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 282, in fetch_chapter
    if clean_name(video_name) not in current_files:
                                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'current_files' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 336, in download_entire_course
    self.fetch_chapter(chapter, chapters_pad_length, delay)
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 282, in fetch_chapter
    if clean_name(video_name) not in current_files:
                                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'current_files' where it is not associated with a value

Current: 0. Welcome/01. Introduction.mp4 @720p
Skipping already existing video...
Downloading subtitles..

Current: 1. Cameras and Lenses/01. Understanding the basics of a camera.mp4 @720p
Skipping already existing video...
Downloading subtitles..

Current: 1. Cameras and Lenses/02. Exploring the basics of a DSLR.mp4 @720p
Skipping already existing video...
Downloading subtitles..

Current: 1. Cameras and Lenses/03. Understanding mirrorless cameras.mp4 @720p
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 336, in download_entire_course
    self.fetch_chapter(chapter, chapters_pad_length, delay)
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 282, in fetch_chapter
    if clean_name(video_name) not in current_files:
                                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'current_files' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 336, in download_entire_course
    self.fetch_chapter(chapter, chapters_pad_length, delay)
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 282, in fetch_chapter
    if clean_name(video_name) not in current_files:
                                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'current_files' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 336, in download_entire_course
    self.fetch_chapter(chapter, chapters_pad_length, delay)
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 282, in fetch_chapter
    if clean_name(video_name) not in current_files:
                                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'current_files' where it is not associated with a value

Current: 0. Welcome/01. Introduction.mp4 @720p
Skipping already existing video...
Downloading subtitles..

Current: 1. Cameras and Lenses/01. Understanding the basics of a camera.mp4 @720p
Skipping already existing video...
Downloading subtitles..

Current: 1. Cameras and Lenses/02. Exploring the basics of a DSLR.mp4 @720p
Skipping already existing video...
Downloading subtitles..

Current: 1. Cameras and Lenses/03. Understanding mirrorless cameras.mp4 @720p
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Skipping already existing video...
Downloading subtitles..
This video is locked, you probably need a premium account
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 336, in download_entire_course
    self.fetch_chapter(chapter, chapters_pad_length, delay)
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 282, in fetch_chapter
    if clean_name(video_name) not in current_files:
                                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'current_files' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 336, in download_entire_course
    self.fetch_chapter(chapter, chapters_pad_length, delay)
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 282, in fetch_chapter
    if clean_name(video_name) not in current_files:
                                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'current_files' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 336, in download_entire_course
    self.fetch_chapter(chapter, chapters_pad_length, delay)
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 282, in fetch_chapter
    if clean_name(video_name) not in current_files:
                                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'current_files' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 336, in download_entire_course
    self.fetch_chapter(chapter, chapters_pad_length, delay)
  File "/usr/local/lib/python3.11/site-packages/llvd/app.py", line 282, in fetch_chapter
    if clean_name(video_name) not in current_files:
                                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'current_files' where it is not associated with a value
```

**Comment by knowbee** [comment]
#105
